---
title: "`r str_to_title(param)`"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
---


```{r, echo=F}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
p1 = result[[2]] %>%
        ggplot() +
        aes(x = Date, y = Calories) +
        geom_line(size = 1.6, colour = "#cb181d") +
        labs(x = "Time", y = "Calorie", title = "", subtitle = "Daily")+
        theme_minimal()
p1 = p1 + expand_limits(y = 0)
x <- result[[2]] %>% mutate(Date=factor(Date)) %>% select(- Calories) %>% gather( .,Nutrients, Total, Protein:Fat, factor_key=TRUE)
p2 =    x %>% ggplot(.) +
        aes(x = Date, fill = Nutrients, weight = Total) +
        geom_bar(position = "fill")

p3 = result[[1]] %>%
        group_by(Name) %>%
        dplyr::summarise(Calories=sum(Calories)) %>%
        arrange(- Calories) %>%
  ggplot(.) +
  aes(x = Name, weight = Calories) +
  geom_bar(fill = "#B22222") +
  labs(title = "Food consumed total")
```

Overview
=======================================================================

### Body Measurments

```{r, echo=F, }

body_data = read.xlsx(origin, "measurements", detectDates = T) %>% melt(., measure.vars = 2:length((.)
names(body_data) <- c("Date", "Area", "Value")
body_monitor =  body_data %>% ggplot(., aes(x=Date, y=Value, group=Area, color=Area)) + geom_line()
ggplotly(body_monitor)

```

### Calorie Intake Over Time

```{r, echo=F, }
ggplotly(p1)
```

Detail
=======================================================================

### Macro-Nutrients Ratio

```{r, echo=F, }
ggplotly(p2)
```

### Food

```{r, echo=F, }
ggplotly(p3)
```





