version: '3.8'
services:
  plumber:
      build:
          dockerfile: ./Dockerfile
          context: .
      image: healthmoniteur
      container_name: healthmoniteur
      volumes:
      - /data/Libraries/Documents/diet/:/data
      ports:
      - 80:80

