name: container-build-push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish Docker Image to GitHub Packages Registry
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.TOKEN }}
          image-name: foodMoniteur
          image-tag: latest
          extract-git-tag: false

        

